
//TODO: Block if accessed as third party site
var blocedThirdParties = [
	"twitter.com",
	"linkedin.com",
	"stumble-upon.com",
	"slashdot.org",
	"facebook.net",
	"plusone.google.com",
	"gravatar.com",
	"disqus.com"];

//TODO: ClickTracking
/*
	"bit.ly",
	"feedburner.com",
	"adf.ly",
	"",
	"",
	"",
	"",
*/
	
var blockedDomains = [
	"ad4game.com",
	"adbrite.com",
	"addthis.com",
	"adjuggler.net",
	"adk2.com",
	"adonion.com",
	"adroll.com",
	"adserve.com",
	"adtechus.com",
	"affbuzzads.com",
	"buysellads.com",
	"chartbeat.com",
	"delicious.com",
	"doubleclick.net",
	"googleadservices.com",
	"googlesyndication.com",
	"google-analytics.com",
	"histats.com",
	"imrworldwide.com",
	"infolinks.com",
	"media6degrees.com",
	"mochiads.com",
	"netseer.com",
	"newrelic.com",
	"optify.net",
	"outbrain.com",
	"pagead.l.google.com",
	"partnerad.l.google.com",
	"quantserve.com",
	"revsci.net",
	"scorecardresearch.com",
	"shareaholic.com",
	"sharethis.com",
	"sitemeter.com",
	"sitestat.com",
	"skimresources.com",
	"snap.com",
	"socialstatistics.com",
	"specificclick.net",
	"statcounter.com",
	"stats.wordpress.com",
	"sublimevideo.net",
	"twittercounter.com",
	"webtrendslive.com",
	"woopra.com",
	"xtendmedia.com",
	"yieldmanager.com",
	"zedo.com"];


